require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
  - 'bin/**/*'
  - 'db/**/*'
  - 'lib/tasks/**/*'
  - 'log/**/*'
  - 'public/**/*'
  - 'storage/**/*'
  - 'tmp/**/*'
  - 'vendor/**/*'
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  Enabled: false

Rails/Output:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
