version: "3.3"

services:
  db:
    image: postgres:11.6-alpine
    container_name: author-list-challenge_postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  web:
    build: .
    container_name: author-list-challenge
    command: /bin/bash
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/author-list-challenge
    depends_on:
      - db
    env_file:
      - .env
