default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>

  timeout: 5000

development:
  <<: *default
  database: author-list-challenge_development

test:
  <<: *default
  database: author-list-challenge_test

production:
  <<: *default
  database: author-list-challenge_production
